# pipeline: master
# dev -> [master]
# gamer-companion.bhxsites.com.br

on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  # react build
  build:
    name: nodejs build
    runs-on: ubuntu-latest

    # default values
    # if not, you have to put working-directory in each run call
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: clone respository
        uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: npm install
      - name: run build
        run: npm run build
      - name: save artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: react-app/build

  # deploy front react
  web-deploy:
    needs: build
    name: 🎉 Deploy front
    runs-on: ubuntu-latest

    steps:
      # get build code
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # efm.bhxsites.com.br
      - name: 📂 Sync files - gamer-companion.bhxsites.com.br
        # using 4.1.0 has a bug of permission 550
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: react-github-actions-build/
          server-dir: gamer-companion.bhxsites.com.br/
